name: CI-Tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
      - name: Build and Tests
        run: sbt -v -Dfile.encoding=UTF-8 clean coverage test coverageReport --timings